---
- hosts: vagranthosts
  gather_facts: true
  become: yes
  remote_user: vagrant 
  tasks:
    - name: install packages
      command: /sbin/apk add unzip curl wget wireguard-tools open-iscsi
      
    - name: Update repositories and install wget and curl packages
      community.general.apk:
        name: wget,curl
        update_cache: true
        
    - name: mount shared root FS 
      command: mount --make-shared /
     
    - name: Create start file make-shared-root.start
      copy:
        dest: /etc/local.d/make-shared-root.start
        content: |
          mount --make-shared /
          mount --make-shared /vagrant_shared

    - name: Enable local.d on startup
      command: rc-update add local default 
    
    - name: start local.d 
      command: rc-service local start

- hosts: master
  become: yes
  remote_user: vagrant
  tasks:
    - name: Install metallb
      command: /usr/local/bin/kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.9/config/manifests/metallb-native.yaml
    
    - name: Copy metallb ip pool yaml
      copy:
        src: ip-pool.yaml
        dest: /tmp/ip-pool.yaml
        owner: vagrant
        group: vagrant
        mode: '0755'
        
    - name: Wait for metallb pods to be running
      command: sleep 120
    
    - name: Install metallb ip-pool
      command: /usr/local/bin/kubectl apply -f /tmp/ip-pool.yaml
   
    - name: Create argocd NS
      command: /usr/local/bin/kubectl create ns argocd
      
    - name: Install argocd 
      command: /usr/local/bin/kubectl -n argocd apply -f https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml
      register: command_output

    - debug:
        var: command_output.stdout_lines
